baseurl = "https://brave-bose-6d81f1.netlify.com"
languageCode = "en-us"
title = "Graphic and UI designer"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Charlotte Wray"
	description = "Graphic and UI designer"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Charlotte Wray"

		[params.navigation.links]
			about     = "About"
			#services  = "About"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Charlotte Wray - graphic and UI designer"
		subtitle   = "currently designing thoughtful campaign webpages and sales enablement tools for Fujifilm's graphic systems devision."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Indroduction"
		description = "Hi, I'm Charlotte,  I love creating great looking graphics and delving into the world of building user experiences."
		buttonText  = "See my work"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Studing interaction design – University"
            description = "Completing an IxD mobile app project focusing on an airport traveller's journey.  "

        [[params.services.list]]
						icon = "fa-paper-plane"
						title = "Graphic design – Fujifilm"
						description = "Refining and learning core principles in visual design for a vareity of materials."

				[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Web development and design – Fujifilm"
            description = "Begin developing web pages for products and campaigns; design and coding."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Graphics and UI design – Fujifilm"
            description = "Lead designer on the visual design of campaigns and the user's digital journey."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "See my curriculum vitae"

		[params.aside.button]
			text = "Download now"
			link = "https://www.dropbox.com/s/8o7gf7yi3sc0n82/Charlotte%20Wray%20-%20Graphic%20and%20UI%20designer%20-%20Curriculum%20Vitae.pdf?dl=0"

	# Contact section
	[params.contact]
		#headline = "Work inquiry, question or something else? <a>Email me<a>"
		#description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		#phone = "123-456-6789"
		#email = "me@charlottewray.co.uk"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
